# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'le_alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.addbutton = QtWidgets.QPushButton(self.centralwidget)
        self.addbutton.setObjectName("addbutton")
        self.gridLayout.addWidget(self.addbutton, 0, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 4)
        self.timer_switch = QtWidgets.QPushButton(self.centralwidget)
        self.timer_switch.setObjectName("timer_switch")
        self.gridLayout.addWidget(self.timer_switch, 2, 3, 1, 1)
        self.Alarm_switch = QtWidgets.QPushButton(self.centralwidget)
        self.Alarm_switch.setObjectName("Alarm_switch")
        self.gridLayout.addWidget(self.Alarm_switch, 2, 0, 1, 1)
        self.stopwatch_switch = QtWidgets.QPushButton(self.centralwidget)
        self.stopwatch_switch.setObjectName("stopwatch_switch")
        self.gridLayout.addWidget(self.stopwatch_switch, 2, 2, 1, 1)
        self.worldtime_switch = QtWidgets.QPushButton(self.centralwidget)
        self.worldtime_switch.setObjectName("worldtime_switch")
        self.gridLayout.addWidget(self.worldtime_switch, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addbutton.setText(_translate("MainWindow", "Добавить"))
        self.timer_switch.setText(_translate("MainWindow", "Таймер"))
        self.Alarm_switch.setText(_translate("MainWindow", "Будильник"))
        self.stopwatch_switch.setText(_translate("MainWindow", "Секундомер"))
        self.worldtime_switch.setText(_translate("MainWindow", "Часы"))
