# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pathetic_Clock.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Alarm_switch = QtWidgets.QPushButton(self.centralwidget)
        self.Alarm_switch.setObjectName("Alarm_switch")
        self.horizontalLayout.addWidget(self.Alarm_switch)
        self.worldtime_switch = QtWidgets.QPushButton(self.centralwidget)
        self.worldtime_switch.setObjectName("worldtime_switch")
        self.horizontalLayout.addWidget(self.worldtime_switch)
        self.stopwatch_switch = QtWidgets.QPushButton(self.centralwidget)
        self.stopwatch_switch.setObjectName("stopwatch_switch")
        self.horizontalLayout.addWidget(self.stopwatch_switch)
        self.timer_switch = QtWidgets.QPushButton(self.centralwidget)
        self.timer_switch.setObjectName("timer_switch")
        self.horizontalLayout.addWidget(self.timer_switch)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Alarm_switch.setText(_translate("MainWindow", "Будильник"))
        self.worldtime_switch.setText(_translate("MainWindow", "Часы"))
        self.stopwatch_switch.setText(_translate("MainWindow", "Секундомер"))
        self.timer_switch.setText(_translate("MainWindow", "Таймер"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
