from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(193, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setEnabled(True)
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.startbutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startbutton.setObjectName("startbutton")
        self.verticalLayout.addWidget(self.startbutton)
        self.stopbutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopbutton.setObjectName("stopbutton")
        self.verticalLayout.addWidget(self.stopbutton)
        self.resetbutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetbutton.setObjectName("resetbutton")
        self.verticalLayout.addWidget(self.resetbutton)
        self.beginthing = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.beginthing.setObjectName("beginthing")
        self.verticalLayout.addWidget(self.beginthing)
        self.groupbox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupbox.setObjectName("groupbox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupbox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 111, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.backwardsstart = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.backwardsstart.setObjectName("backwardsstart")
        self.verticalLayout_2.addWidget(self.backwardsstart)
        self.backwardsstopbutton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.backwardsstopbutton.setObjectName("backwardsstopbutton")
        self.verticalLayout_2.addWidget(self.backwardsstopbutton)
        self.verticalLayout.addWidget(self.groupbox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startbutton.setText(_translate("Form", "Старт"))
        self.stopbutton.setText(_translate("Form", "Стоп"))
        self.resetbutton.setText(_translate("Form", "Сбросить"))
        self.groupbox.setTitle(_translate("Form", "Обратный отсчет"))
        self.backwardsstart.setText(_translate("Form", "Старт"))
        self.backwardsstopbutton.setText(_translate("Form", "Стоп"))
