# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timerdes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(252, 350)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 241, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.hourbox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.hourbox.setMaximum(23)
        self.hourbox.setObjectName("hourbox")
        self.verticalLayout.addWidget(self.hourbox)
        self.hour = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.hour.setObjectName("hour")
        self.verticalLayout.addWidget(self.hour)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.minbox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.minbox.setMaximum(59)
        self.minbox.setObjectName("minbox")
        self.verticalLayout_5.addWidget(self.minbox)
        self.minute = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.minute.setObjectName("minute")
        self.verticalLayout_5.addWidget(self.minute)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.secondbox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.secondbox.setMaximum(59)
        self.secondbox.setObjectName("secondbox")
        self.verticalLayout_4.addWidget(self.secondbox)
        self.sec = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.sec.setObjectName("sec")
        self.verticalLayout_4.addWidget(self.sec)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(330, 160, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_4.setObjectName("spinBox_4")
        self.verticalLayout_3.addWidget(self.spinBox_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.pushbutton = QtWidgets.QPushButton(Form)
        self.pushbutton.setGeometry(QtCore.QRect(60, 170, 121, 23))
        self.pushbutton.setObjectName("pushbutton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hour.setText(_translate("Form", "Часы"))
        self.minute.setText(_translate("Form", "минуты"))
        self.sec.setText(_translate("Form", "секунды"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.pushbutton.setText(_translate("Form", "Старт"))
