# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timesettter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 90)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timeset = QtWidgets.QPushButton(self.centralwidget)
        self.timeset.setGeometry(QtCore.QRect(0, 10, 131, 21))
        self.timeset.setObjectName("timeset")
        self.settime = QtWidgets.QLabel(self.centralwidget)
        self.settime.setGeometry(QtCore.QRect(200, 10, 271, 21))
        self.settime.setStyleSheet("border: 3px solid blue;")
        self.settime.setText("")
        self.settime.setObjectName("settime")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeset.setText(_translate("MainWindow", "Set Time"))
